package com.bw.fsm.serializer;

public interface DefaultProtocolDefinitions {

    //! Constants, used in the protocol.

    String FSM_PROTOCOL_TYPE_PROTOCOL_VERSION = "DwP1.1";
    int FSM_PROTOCOL_TYPE_OPT_STRING_NONE = 0x10;
    int FSM_PROTOCOL_TYPE_BOOLEAN_TRUE = 0x1F;
    int FSM_PROTOCOL_TYPE_BOOLEAN_FALSE = 0x10;
    int FSM_PROTOCOL_TYPE_INT_4BIT = 0x30;
    int FSM_PROTOCOL_TYPE_INT_12BIT = 0x40;
    int FSM_PROTOCOL_TYPE_INT_20BIT = 0x50;
    int FSM_PROTOCOL_TYPE_INT_28BIT = 0x60;
    int FSM_PROTOCOL_TYPE_INT_36BIT = 0x70;
    int FSM_PROTOCOL_TYPE_INT_44BIT = 0x80;
    int FSM_PROTOCOL_TYPE_INT_52BIT = 0x90;
    int FSM_PROTOCOL_TYPE_INT_60BIT = 0xA0;
    int FSM_PROTOCOL_TYPE_INT_68BIT = 0xB0;
    int FSM_PROTOCOL_TYPE_STRING_LENGTH_4BIT = 0xC0;
    int FSM_PROTOCOL_TYPE_STRING_LENGTH_12BIT = 0xD0;

    int FSM_PROTOCOL_FLAG_HISTORY_TYPE_MASK = 0x03;
    int FSM_PROTOCOL_FLAG_ON_ENTRY = 0x04;
    int FSM_PROTOCOL_FLAG_ON_EXIT = 0x08;
    int FSM_PROTOCOL_FLAG_STATES = 0x10;
    int FSM_PROTOCOL_FLAG_IS_FINAL = 0x20;
    int FSM_PROTOCOL_FLAG_IS_PARALLEL = 0x40;
    int FSM_PROTOCOL_FLAG_DONE_DATA = 0x80;
    int FSM_PROTOCOL_FLAG_INVOKE = 0x100;
    int FSM_PROTOCOL_FLAG_DATA = 0x200;
    int FSM_PROTOCOL_FLAG_HISTORY = 0x400;
    int FSM_PROTOCOL_TYPE_OPT_DATA_VALUE_NONE = 0x0A;

}
